### PR TITLE
Implemented Data Generation, Database Seeding, & Stress Testing

### PR DESCRIPTION
**Pull request by Mjones13**
- Refactored server to be RESTful
- Reformated data generation script for 10M artists
- Created script to generate images
- Created scripts for writing json & csv files
- Created schemas for Postgres & Cassandra
- Created scripts for seeding Postgres & Cassandra
- Refactored database queries
- Created a script to stress test server

### CODE REVIEW

**Review by Saishyuro — APPROVED** [review]
line 63: persistingData will never be undefined, it looks like it will return allArtists, which will be an empty array

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]
db queries need refactoring

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]

**Review by Saishyuro — APPROVED** [review]
Not sure if youve changed your indexes, but if you're referencing artistid in albums as a foreign key, then you may want to index albums to have an index on (albumid, artistid) and songs to index on (albumid, songid)

**Comment by Mjones13** [comment]
- persistingData() was updated and removed in a later commit
- DB Queries have been refactored 
- Indexes were updated in the terminal, now added SQL commands to relevant files

**Pull request merged**
